### ISSUE TITLE
npm run rebuild fails

### ISSUE THREAD

**Issue by vsivsi** [joehand/are-you-around#1]
Hi, saw you post a link on the dat IRC, and thought I'd try it out... Here's as far as it got on my box (OS X 10.11.6).  Note that it fails similarly with both node 4.5.0 and 6.4.0 (shown).

``` sh
npm run rebuild

> are-you-around@1.0.0 rebuild /Users/vsi/are-you-around
> npm rebuild --runtime=electron --target=1.3.4 --disturl=https://atom.io/download/atom-shell --build-from-source


> electron-prebuilt@1.3.4 postinstall /Users/vsi/are-you-around/node_modules/electron-prebuilt
> node install.js


> leveldown@1.4.6 install /Users/vsi/are-you-around/node_modules/leveldown
> prebuild --install

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/leveldb_main.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
../src/batch.cc:71:50: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                 ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:3264:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/batch.cc:74:50: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                 ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:3264:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
2 warnings generated.
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
  CXX(target) Release/obj.target/leveldown/src/database.o
../src/database.cc:166:48: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                               ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:3264:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/database.cc:458:16: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
  v8::TryCatch try_catch;
               ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:6777:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
2 warnings generated.
  CXX(target) Release/obj.target/leveldown/src/database_async.o
  CXX(target) Release/obj.target/leveldown/src/iterator.o
../src/iterator.cc:331:50: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                 ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:3264:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/iterator.cc:334:50: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    instance = constructorHandle->GetFunction()->NewInstance(3, argv);
                                                 ^
/Users/vsi/.node-gyp/iojs-1.3.4/deps/v8/include/v8.h:3264:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
2 warnings generated.
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
  SOLINK_MODULE(target) Release/leveldown.node
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> sodium-prebuilt@1.0.22 install /Users/vsi/are-you-around/node_modules/sodium-prebuilt
> prebuild --install --preinstall make

./autogen.sh: line 14: aclocal: command not found
make: *** [configure] Error 127
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (/Users/vsi/are-you-around/node_modules/prebuild/error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (/Users/vsi/are-you-around/node_modules/prebuild/util.js:113:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--runtime=electron" "--target=1.3.4" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! sodium-prebuilt@1.0.22 install: `prebuild --install --preinstall make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the sodium-prebuilt@1.0.22 install script 'prebuild --install --preinstall make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install --preinstall make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vsi/are-you-around/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! are-you-around@1.0.0 rebuild: `npm rebuild --runtime=electron --target=1.3.4 --disturl=https://atom.io/download/atom-shell --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the are-you-around@1.0.0 rebuild script 'npm rebuild --runtime=electron --target=1.3.4 --disturl=https://atom.io/download/atom-shell --build-from-source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the are-you-around package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm rebuild --runtime=electron --target=1.3.4 --disturl=https://atom.io/download/atom-shell --build-from-source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs are-you-around
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls are-you-around
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vsi/are-you-around/npm-debug.log
```

**Comment by vsivsi** [comment]
Looks like `brew install automake` fixed it.  You might want to note that GNU `automake` is a build dependency (I typically use `cmake` for my projects...)
